### PR TITLE
ip clearance review of 34222e85498b3bda67279f67735de3f170e676c8

### PR DESCRIPTION
**Pull request by pdinc-oss**
I reviewed the files you worked on, the 2 following files are unresolved at this time for inclusion:

src/dev-tool/fn-format.c
src/dev-tool/Tcformat.h

All other files are eligible to be merged.

Could you please update those 2 files with what is "old" copied code and what is new "Apache 2.0" licensed code? I cannot use git blame, since the files are 100% your edits per git.

I will spend some time this week if you cannot.

Also can you digitally (GPG) sign your last commit before merge?

Thanks!

### CODE REVIEW

**Comment by f-n** [comment]
at least I tried to sign my commit. I'm not sure whether it was correct,
I used the command for the first time:
git commit -a -SE8B5F9BE --amend

Falk

**Comment by jpyeron** [comment]
excellent, I see it as signed. Did you ever publish the key anywhere?

e.g. publishing to MIT:

```
root@black7 /projects/ciphershed
$ gpg --list-keys
/home/root/.gnupg/pubring.gpg
-----------------------------
pub   2048R/DA0848AD 2014-06-24 [expires: 2016-06-19]
uid                  Jason Pyeron <jpyeron@pdinc.us>
sub   2048R/74189519 2014-06-24 [expires: 2016-06-19]

root@black7 /projects/ciphershed
$ gpg --keyserver pgp.mit.edu --send-key DA0848AD
gpg: sending key DA0848AD to hkp server pgp.mit.edu
```

or exporting, for import with github.com (https://github.com/settings/keys):

```
root@black7 /projects/ciphershed
$ gpg -a --export DA0848AD
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1

mQENBFOpuQEBCACsdBxA5fEXxv+OowbNNQYzrM3wPpJBhBCxRYM1F+iyqhBw9iq/
sNdm0Q7BPloK9w26jZHuUdSAoQsVA+XrdfrGqPRc3FDLDMxXNNeAXUmtpBObEsxu
PHetKt2wljln//Nm8GEww6OLy6TbsB9h9goHPEAU3ijDWtvfrrcBSk78Xh7c3hyv
D8/1YQcc3LtJHER/plv1jSbGja3V4Ux2oX60BrrMU9g8DYPlgCdkvfhkn3tjrAAt
TobcpbA4gO5q1GH8Xj75NnXBwyRCYmhrzU+nUZZmMS6tb86SNcA7r7LWLtbcFtoq
M9ZQS8YFbMZOt1Zv5ddGpUpittOFGscFN9QFABEBAAG0H0phc29uIFB5ZXJvbiA8
anB5ZXJvbkBwZGluYy51cz6JAT4EEwECACgCGwMGCwkIBwMCBhUIAgkKCwQWAgMB
Ah4BAheABQJWeNPFBQkDvGi6AAoJEI1rWYTaCEitvFwH/1qaDpCP1k9zM874UE8B
/eRy4Swj1x0kFS8v1aZXHwhIkzJEZCNO/21U8UaDeOtk8hvnMNFssCK1LmdLisOn
WrpBLSnY9X9CSvxbZ+tNJtJYkTHA4/uktZ+V3T5J3n0eBc9Bnb1gup4ZknAZvTlm
aRSHqpcb3AYu71C3oelMppityIAPB2ZSwGbdypwmCDyD1vpPgdiQHw5E+WWWE7OQ
1Mz6gOAYP82nnb47lBlJ3S+L3P/IOIcUu+cfSEY02sLA1ZQZZ7OKTFJDg7o1JVgB
W/b//oc2sCRJgdJmhx7VjFbXYiMU3G1/kjzkzYtS5psLiBD2bHAMydIHeKcbtcDg
gLm5AQ0EU6m5AQEIAKN4R7qEDff4Lzone4z7EXc0HVoLyCGzEUtgjFhw3rKX+e2k
7caMhMtDDBb1sGyK68NlbXt2TaSbUbMSJ5w0c6Ve/oOD3Drv6u8HCTpup1kWGziz
cX8F4Z38TVhktpGSerfb9nw6qZV9jpsCJO5upxYb/84YSiR840vmhoqJdWG6FDF8
OkGdSSynebpIN5Tmgebl0j+d6aXT7aRM4FhbyFQFIq1vQQwO87jmnY7lKPafo78J
GBQc8acTjbeTC2lmM/0F8z2465PjprrK5uhBywGkSVlRgCXev79CmvHd7LAu99v5
AAtbGJ0xtL5FwG+heM4dlk8XoK9QG6fhVenN3UUAEQEAAYkBJQQYAQIADwIbDAUC
VnjT0wUJA7xozQAKCRCNa1mE2ghIrXdIB/wKxBbT94KfMLDat7V1dVbYPhiywUJB
mpRpuqBXjAMi3mSOCKVfUrRfyYQwCtpwPCoiMEdCrS1iy56bqXIuLNY7gAVwp8sU
GCom1GyFYGPhjPanciEswDLcU9fYokJ9bhUsYT+cRfomYZh6VtZ8So+YpTpswqvj
z+jU3jBvnukkEXSia2Vi2Y0Tt+DgoAbrTWqxSF9iX/QpGuCylZFUlVKYSe1BbjS+
WftUF0UzB3E/+lOoaFiOFCFu+ioPx/CpYQ/DyLNdrc/yCV58tOIZ11TE5Yra+Lv2
fOe1gX4pVDT9ehsJaknWOLQMBx+28EW2tpMiO7LsQchiE6WyWnKPWmBx
=TFKx
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by f-n** [comment]
Yes, I did. When you go to
https://pgp.mit.edu/
and search for my name (Falk Nedwal), the you will find it.

**Comment by pdinc-oss** [comment]
OBE, see https://github.com/f-n/CipherShed/pull/2

**Pull request closed without merging**
